//! Generated by `./gen.rs forward < in.c > out.c`

#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <poll.h>
#include <stdio.h>
#include <sys/mman.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/uio.h>
#include <time.h>
#include <unistd.h>

// dirent.h

__attribute__((weak)) ssize_t sys_getdents64(int fd, void *dirp, size_t count) {
    fprintf(stderr, "weak sys_getdents64() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

ssize_t getdents64(int fd, void *dirp, size_t count) {
    ssize_t ret = sys_getdents64(fd, dirp, count);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

// poll.h

__attribute__((weak)) int sys_poll(struct pollfd *fds, nfds_t nfds, int timeout) {
    fprintf(stderr, "weak sys_poll() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int poll(struct pollfd *fds, nfds_t nfds, int timeout) {
    int ret = sys_poll(fds, nfds, timeout);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

// sys/mman.h

__attribute__((weak)) int sys_mlock(const void *addr, size_t len) {
    fprintf(stderr, "weak sys_mlock() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int mlock(const void *addr, size_t len) {
    int ret = sys_mlock(addr, len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_mlockall(int flags) {
    fprintf(stderr, "weak sys_mlockall() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int mlockall(int flags) {
    int ret = sys_mlockall(flags);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_munlock(const void *addr, size_t len) {
    fprintf(stderr, "weak sys_munlock() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int munlock(const void *addr, size_t len) {
    int ret = sys_munlock(addr, len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_munlockall(void) {
    fprintf(stderr, "weak sys_munlockall() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int munlockall(void) {
    int ret = sys_munlockall();

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

// sys/socket.h

__attribute__((weak)) int sys_accept(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len) {
    fprintf(stderr, "weak sys_accept() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int accept(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len) {
    int ret = sys_accept(socket, address, address_len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_bind(int socket, const struct sockaddr *address, socklen_t address_len) {
    fprintf(stderr, "weak sys_bind() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int bind(int socket, const struct sockaddr *address, socklen_t address_len) {
    int ret = sys_bind(socket, address, address_len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_connect(int socket, const struct sockaddr *address, socklen_t address_len) {
    fprintf(stderr, "weak sys_connect() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int connect(int socket, const struct sockaddr *address, socklen_t address_len) {
    int ret = sys_connect(socket, address, address_len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_getpeername(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len) {
    fprintf(stderr, "weak sys_getpeername() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int getpeername(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len) {
    int ret = sys_getpeername(socket, address, address_len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_getsockname(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len) {
    fprintf(stderr, "weak sys_getsockname() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int getsockname(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len) {
    int ret = sys_getsockname(socket, address, address_len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_getsockopt(int socket, int level, int option_name, void *restrict option_value, socklen_t *restrict option_len) {
    fprintf(stderr, "weak sys_getsockopt() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int getsockopt(int socket, int level, int option_name, void *restrict option_value, socklen_t *restrict option_len) {
    int ret = sys_getsockopt(socket, level, option_name, option_value, option_len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_listen(int socket, int backlog) {
    fprintf(stderr, "weak sys_listen() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int listen(int socket, int backlog) {
    int ret = sys_listen(socket, backlog);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_setsockopt(int socket, int level, int option_name, const void *option_value, socklen_t option_len) {
    fprintf(stderr, "weak sys_setsockopt() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int setsockopt(int socket, int level, int option_name, const void *option_value, socklen_t option_len) {
    int ret = sys_setsockopt(socket, level, option_name, option_value, option_len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_shutdown(int socket, int how) {
    fprintf(stderr, "weak sys_shutdown() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int shutdown(int socket, int how) {
    int ret = sys_shutdown(socket, how);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_socket(int domain, int type, int protocol) {
    fprintf(stderr, "weak sys_socket() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int socket(int domain, int type, int protocol) {
    int ret = sys_socket(domain, type, protocol);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) ssize_t sys_recvfrom(int socket, void *restrict buffer, size_t length, int flags, struct sockaddr *restrict address, socklen_t *restrict address_len) {
    fprintf(stderr, "weak sys_recvfrom() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

ssize_t recvfrom(int socket, void *restrict buffer, size_t length, int flags, struct sockaddr *restrict address, socklen_t *restrict address_len) {
    ssize_t ret = sys_recvfrom(socket, buffer, length, flags, address, address_len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) ssize_t sys_recv(int socket, void *buffer, size_t length, int flags) {
    fprintf(stderr, "weak sys_recv() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

ssize_t recv(int socket, void *buffer, size_t length, int flags) {
    ssize_t ret = sys_recv(socket, buffer, length, flags);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) ssize_t sys_send(int socket, const void *buffer, size_t length, int flags) {
    fprintf(stderr, "weak sys_send() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

ssize_t send(int socket, const void *buffer, size_t length, int flags) {
    ssize_t ret = sys_send(socket, buffer, length, flags);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) ssize_t sys_sendto(int socket, const void *message, size_t length, int flags, const struct sockaddr *dest_addr, socklen_t dest_len) {
    fprintf(stderr, "weak sys_sendto() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

ssize_t sendto(int socket, const void *message, size_t length, int flags, const struct sockaddr *dest_addr, socklen_t dest_len) {
    ssize_t ret = sys_sendto(socket, message, length, flags, dest_addr, dest_len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

// sys/stat.h

__attribute__((weak)) int sys_fchmod(int fildes, mode_t mode) {
    fprintf(stderr, "weak sys_fchmod() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int fchmod(int fildes, mode_t mode) {
    int ret = sys_fchmod(fildes, mode);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_fstat(int fildes, struct stat *buf) {
    fprintf(stderr, "weak sys_fstat() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int fstat(int fildes, struct stat *buf) {
    int ret = sys_fstat(fildes, buf);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_lstat(const char *restrict path, struct stat *restrict buf) {
    fprintf(stderr, "weak sys_lstat() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int lstat(const char *restrict path, struct stat *restrict buf) {
    int ret = sys_lstat(path, buf);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_mkdir(const char *path, mode_t mode) {
    fprintf(stderr, "weak sys_mkdir() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int mkdir(const char *path, mode_t mode) {
    int ret = sys_mkdir(path, mode);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_stat(const char *restrict path, struct stat *restrict buf) {
    fprintf(stderr, "weak sys_stat() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int stat(const char *restrict path, struct stat *restrict buf) {
    int ret = sys_stat(path, buf);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

// sys/time.h

__attribute__((weak)) int sys_gettimeofday(struct timeval *restrict tp, void *restrict tzp) {
    fprintf(stderr, "weak sys_gettimeofday() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int gettimeofday(struct timeval *restrict tp, void *restrict tzp) {
    int ret = sys_gettimeofday(tp, tzp);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

// sys/uio.h

__attribute__((weak)) ssize_t sys_readv(int fildes, const struct iovec *iov, int iovcnt) {
    fprintf(stderr, "weak sys_readv() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

ssize_t readv(int fildes, const struct iovec *iov, int iovcnt) {
    ssize_t ret = sys_readv(fildes, iov, iovcnt);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) ssize_t sys_writev(int fildes, const struct iovec *iov, int iovcnt) {
    fprintf(stderr, "weak sys_writev() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

ssize_t writev(int fildes, const struct iovec *iov, int iovcnt) {
    ssize_t ret = sys_writev(fildes, iov, iovcnt);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

// fcntl.h

__attribute__((weak)) int sys_faccessat(int fd, const char *path, int amode, int flag) {
    fprintf(stderr, "weak sys_faccessat() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int faccessat(int fd, const char *path, int amode, int flag) {
    int ret = sys_faccessat(fd, path, amode, flag);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

// time.h

__attribute__((weak)) int sys_clock_getres(clockid_t clock_id, struct timespec *res) {
    fprintf(stderr, "weak sys_clock_getres() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int clock_getres(clockid_t clock_id, struct timespec *res) {
    int ret = sys_clock_getres(clock_id, res);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_clock_gettime(clockid_t clock_id, struct timespec *tp) {
    fprintf(stderr, "weak sys_clock_gettime() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int clock_gettime(clockid_t clock_id, struct timespec *tp) {
    int ret = sys_clock_gettime(clock_id, tp);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_clock_settime(clockid_t clock_id, const struct timespec *tp) {
    fprintf(stderr, "weak sys_clock_settime() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int clock_settime(clockid_t clock_id, const struct timespec *tp) {
    int ret = sys_clock_settime(clock_id, tp);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_nanosleep(const struct timespec *rqtp, struct timespec *rmtp) {
    fprintf(stderr, "weak sys_nanosleep() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int nanosleep(const struct timespec *rqtp, struct timespec *rmtp) {
    int ret = sys_nanosleep(rqtp, rmtp);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

// unistd.h

__attribute__((weak)) int sys_access(const char *path, int amode) {
    fprintf(stderr, "weak sys_access() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int access(const char *path, int amode) {
    int ret = sys_access(path, amode);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_chdir(const char *path) {
    fprintf(stderr, "weak sys_chdir() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int chdir(const char *path) {
    int ret = sys_chdir(path);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_close(int fildes) {
    fprintf(stderr, "weak sys_close() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int close(int fildes) {
    int ret = sys_close(fildes);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_dup(int fildes) {
    fprintf(stderr, "weak sys_dup() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int dup(int fildes) {
    int ret = sys_dup(fildes);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_dup2(int fildes, int fildes2) {
    fprintf(stderr, "weak sys_dup2() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int dup2(int fildes, int fildes2) {
    int ret = sys_dup2(fildes, fildes2);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) off_t sys_lseek(int fildes, off_t offset, int whence) {
    fprintf(stderr, "weak sys_lseek() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

off_t lseek(int fildes, off_t offset, int whence) {
    off_t ret = sys_lseek(fildes, offset, whence);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) ssize_t sys_read(int fildes, void *buf, size_t nbyte) {
    fprintf(stderr, "weak sys_read() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

ssize_t read(int fildes, void *buf, size_t nbyte) {
    ssize_t ret = sys_read(fildes, buf, nbyte);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_rmdir(const char *path) {
    fprintf(stderr, "weak sys_rmdir() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int rmdir(const char *path) {
    int ret = sys_rmdir(path);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_truncate(const char *path, off_t length) {
    fprintf(stderr, "weak sys_truncate() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int truncate(const char *path, off_t length) {
    int ret = sys_truncate(path, length);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_ftruncate(int fildes, off_t length) {
    fprintf(stderr, "weak sys_ftruncate() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int ftruncate(int fildes, off_t length) {
    int ret = sys_ftruncate(fildes, length);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) int sys_unlink(const char *path) {
    fprintf(stderr, "weak sys_unlink() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

int unlink(const char *path) {
    int ret = sys_unlink(path);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

__attribute__((weak)) ssize_t sys_write(int fildes, const void *buf, size_t nbyte) {
    fprintf(stderr, "weak sys_write() called. Symbol was not replaced!\n");
    errno = ENOSYS;
    return -1;
}

ssize_t write(int fildes, const void *buf, size_t nbyte) {
    ssize_t ret = sys_write(fildes, buf, nbyte);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}
