//! Generated by `./forward-gen.rs < forward-in.c > forward.c`

#include <errno.h>
#include <sys/socket.h>


int sys_socket(int domain, int type, int protocol);

int socket(int domain, int type, int protocol) {
    int ret = sys_socket(domain, type, protocol);

    if (ret < 0) {
        errno = -ret;
        ret = -1;
    }

    return ret;
}

int sys_accept(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len);

int accept(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len) {
    int ret = sys_accept(socket, address, address_len);

    if (ret < 0) {
        errno = -ret;
        ret = -1;
    }

    return ret;
}

int sys_listen(int socket, int backlog);

int listen(int socket, int backlog) {
    int ret = sys_listen(socket, backlog);

    if (ret < 0) {
        errno = -ret;
        ret = -1;
    }

    return ret;
}

int sys_bind(int socket, const struct sockaddr *address, socklen_t address_len);

int bind(int socket, const struct sockaddr *address, socklen_t address_len) {
    int ret = sys_bind(socket, address, address_len);

    if (ret < 0) {
        errno = -ret;
        ret = -1;
    }

    return ret;
}

int sys_connect(int socket, const struct sockaddr *address, socklen_t address_len);

int connect(int socket, const struct sockaddr *address, socklen_t address_len) {
    int ret = sys_connect(socket, address, address_len);

    if (ret < 0) {
        errno = -ret;
        ret = -1;
    }

    return ret;
}

int sys_getsockname(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len);

int getsockname(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len) {
    int ret = sys_getsockname(socket, address, address_len);

    if (ret < 0) {
        errno = -ret;
        ret = -1;
    }

    return ret;
}

int sys_setsockopt(int socket, int level, int option_name, const void *option_value, socklen_t option_len);

int setsockopt(int socket, int level, int option_name, const void *option_value, socklen_t option_len) {
    int ret = sys_setsockopt(socket, level, option_name, option_value, option_len);

    if (ret < 0) {
        errno = -ret;
        ret = -1;
    }

    return ret;
}

int sys_getsockopt(int socket, int level, int option_name, void *restrict option_value, socklen_t *restrict option_len);

int getsockopt(int socket, int level, int option_name, void *restrict option_value, socklen_t *restrict option_len) {
    int ret = sys_getsockopt(socket, level, option_name, option_value, option_len);

    if (ret < 0) {
        errno = -ret;
        ret = -1;
    }

    return ret;
}

int sys_getpeername(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len);

int getpeername(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len) {
    int ret = sys_getpeername(socket, address, address_len);

    if (ret < 0) {
        errno = -ret;
        ret = -1;
    }

    return ret;
}

ssize_t sys_send(int socket, const void *buffer, size_t length, int flags);

ssize_t send(int socket, const void *buffer, size_t length, int flags) {
    int ret = sys_send(socket, buffer, length, flags);

    if (ret < 0) {
        errno = -ret;
        ret = -1;
    }

    return ret;
}

int sys_shutdown(int socket, int how);

int shutdown(int socket, int how) {
    int ret = sys_shutdown(socket, how);

    if (ret < 0) {
        errno = -ret;
        ret = -1;
    }

    return ret;
}

ssize_t sys_recv(int socket, void *buffer, size_t length, int flags);

ssize_t recv(int socket, void *buffer, size_t length, int flags) {
    int ret = sys_recv(socket, buffer, length, flags);

    if (ret < 0) {
        errno = -ret;
        ret = -1;
    }

    return ret;
}

ssize_t sys_sendto(int socket, const void *message, size_t length, int flags, const struct sockaddr *dest_addr, socklen_t dest_len);

ssize_t sendto(int socket, const void *message, size_t length, int flags, const struct sockaddr *dest_addr, socklen_t dest_len) {
    int ret = sys_sendto(socket, message, length, flags, dest_addr, dest_len);

    if (ret < 0) {
        errno = -ret;
        ret = -1;
    }

    return ret;
}

ssize_t sys_recvfrom(int socket, void *restrict buffer, size_t length, int flags, struct sockaddr *restrict address, socklen_t *restrict address_len);

ssize_t recvfrom(int socket, void *restrict buffer, size_t length, int flags, struct sockaddr *restrict address, socklen_t *restrict address_len) {
    int ret = sys_recvfrom(socket, buffer, length, flags, address, address_len);

    if (ret < 0) {
        errno = -ret;
        ret = -1;
    }

    return ret;
}
