libc_a_SOURCES += \
	%D%/alloc.c \
	%D%/context.S \
	%D%/environ.c \
	%D%/errno.c \
	%D%/fcntl.c \
	%D%/forward.c \
	%D%/inet_ntoa.c \
	%D%/inet.c \
	%D%/ioctl.c \
	%D%/makecontext.c \
	%D%/mman.c \
	%D%/netdb.c \
	%D%/pwd.c \
	%D%/resource.c \
	%D%/signal.c \
	%D%/stdlib.c \
	%D%/stub.c \
	%D%/time.c \
	%D%/unistd.c
