//! Generated by `./gen.rs stub < in.c > out.c`

#include <errno.h>
#include <unistd.h>

// unistd.h

int chown(const char *path, uid_t owner, gid_t group) {
    errno = ENOSYS;
    return -1;
}

int execve(const char *path, char *const argv[], char *const envp[]) {
    errno = ENOSYS;
    return -1;
}
