//! Generated by `./gen.rs stub < in.c > out.c`

#include <errno.h>
#include <sched.h>
#include <signal.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/times.h>
#include <sys/wait.h>
#include <unistd.h>

// sched.h

int sched_getparam(pid_t pid, struct sched_param *param) {
    errno = ENOSYS;
    return -1;
}

int sched_getscheduler(pid_t pid) {
    errno = ENOSYS;
    return -1;
}

int sched_setparam(pid_t pid, const struct sched_param *param) {
    errno = ENOSYS;
    return -1;
}

int sched_setscheduler(pid_t pid, int policy, const struct sched_param *param) {
    errno = ENOSYS;
    return -1;
}

// signal.h

int kill(pid_t pid, int sig) {
    errno = ENOSYS;
    return -1;
}

int sigaction(int sig, const struct sigaction *restrict act, struct sigaction *restrict oact) {
    errno = ENOSYS;
    return -1;
}

int sigprocmask(int how, const sigset_t *restrict set, sigset_t *restrict oset) {
    errno = ENOSYS;
    return -1;
}

// sys/socket.h

ssize_t recvmsg(int socket, struct msghdr *message, int flags) {
    errno = ENOSYS;
    return -1;
}

ssize_t sendmsg(int socket, const struct msghdr *message, int flags) {
    errno = ENOSYS;
    return -1;
}

// sys/stat.h

int chmod(const char *path, mode_t mode) {
    errno = ENOSYS;
    return -1;
}

// sys/time.h

int setitimer(int which, const struct itimerval *restrict value, struct itimerval *restrict ovalue) {
    errno = ENOSYS;
    return -1;
}

// sys/times.h

clock_t times(struct tms *buffer) {
    errno = ENOSYS;
    return -1;
}

// sys/wait.h

pid_t wait(int *stat_loc) {
    errno = ENOSYS;
    return -1;
}

pid_t waitpid(pid_t pid, int *stat_loc, int options) {
    errno = ENOSYS;
    return -1;
}

// unistd.h

int chown(const char *path, uid_t owner, gid_t group) {
    errno = ENOSYS;
    return -1;
}

int _execve(const char *path, char *const argv[], char *const envp[]) {
    errno = ENOSYS;
    return -1;
}

int execvpe(const char *file, char *const argv[], char *const envp[]) {
    errno = ENOSYS;
    return -1;
}

pid_t fork(void) {
    errno = ENOSYS;
    return -1;
}

int link(const char *path1, const char *path2) {
    errno = ENOSYS;
    return -1;
}

int pipe(int fildes[2]) {
    errno = ENOSYS;
    return -1;
}

int pipe2(int fildes[2], int flag) {
    errno = ENOSYS;
    return -1;
}

ssize_t readlink(const char *restrict path, char *restrict buf, size_t bufsize) {
    errno = ENOSYS;
    return -1;
}

int symlink(const char *path1, const char *path2) {
    errno = ENOSYS;
    return -1;
}

pid_t vfork(void) {
    errno = ENOSYS;
    return -1;
}
