//! Generated by `./gen.rs stub < in.c > out.c`

#include <errno.h>
#include <unistd.h>

// unistd.h

int chown(const char *path, uid_t owner, gid_t group) {
    errno = ENOSYS;
    return -1;
}

int execl(const char *path, const char *arg0, ... /*, (char *)0 */) {
    errno = ENOSYS;
    return -1;
}

int execle(const char *path, const char *arg0, ... /*, (char *)0, char *const envp[]*/) {
    errno = ENOSYS;
    return -1;
}

int execlp(const char *file, const char *arg0, ... /*, (char *)0 */) {
    errno = ENOSYS;
    return -1;
}

int execv(const char *path, char *const argv[]) {
    errno = ENOSYS;
    return -1;
}

int execve(const char *path, char *const argv[], char *const envp[]) {
    errno = ENOSYS;
    return -1;
}

int execvp(const char *file, char *const argv[]) {
    errno = ENOSYS;
    return -1;
}

int fexecve(int fd, char *const argv[], char *const envp[]) {
    errno = ENOSYS;
    return -1;
}

pid_t fork(void) {
    errno = ENOSYS;
    return -1;
}

int link(const char *path1, const char *path2) {
    errno = ENOSYS;
    return -1;
}
